name: samen1 
description: "De officiële Samen1 app"
publish_to: none
# De versie bestaat uit 3 nummers: major.minor.patch
# Het build nummer moet bij elke release verhoogd worden
version: 0.4.4+44  # <versie>+<buildnummer>

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^6.0.0
  wakelock_plus: ^1.1.4
  package_info_plus: ^8.3.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.2.3
  http: ^1.1.2
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.14.3
  device_info_plus: ^11.3.3
  html: ^0.15.4
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo2.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo2.png"